# Generated by Django 5.1.1 on 2024-10-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mavzu',
            old_name='mavzu_image',
            new_name='image',
        ),
    ]
